project_id = "vyscrpvmxwlpcjqhwulo"

[functions.create-payment]
verify_jwt = false

[functions.onepay-callback]
verify_jwt = false

[functions.update-payment-settings]
verify_jwt = false

[functions.schedule-downgrade]
verify_jwt = false

[functions.cancel-downgrade]
verify_jwt = false
